// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqayratodfpisjwgvubc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxYXlyYXRvZGZwaXNqd2d2dWJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4Mzc5NTAsImV4cCI6MjA2NjQxMzk1MH0.cGpJBLOC9_ig7NfvuiOgrNhA-Z1PFjZp28mfebQUUi4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);